version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "3000:8080"
volumes:
  redis-data: